### ISSUE TITLE
Sugestão:

### ISSUE THREAD

**Issue by higuoliveira98** [wessleysanttos/api_python_test#3]
Ao invés de criar um DAO na mão para abstrair a base em classe, sugiro utilizar um ORM para tal. Para Flask, conheço apenas o SQLAlchemy. Ele abstrai suas tabelas do banco em classes. O lado bom é que você não precisará mexer com SQL na mão, apenas com objetos.

**Comment by wessleysanttos** [comment]
Faz todo sentido mano, vou dar uma pesquisada sobre o SQLAlchemy.
