### ISSUE TITLE
Padronização dos retornos da API

### ISSUE THREAD

**Issue by higuoliveira98** [wessleysanttos/api_python_test#4]
Percebi que você modelou os retornos das requisições da seguinte forma:
`{'blabla': blabla}`
Se uma pessoa desorganizada com esse tipo de padrão pega seu código para dar manutenção, isso pode ser um problema.

Sugiro utilizar NamedTuple para python 3.6 e data classes para python 3.7+ para fazer esse serviço.

Basicamente você cria classes que contém apenas atributos, no caso os atributos que você irá retornar.

Você cria uma instancia dessa classe passando os atributos a ser preenchidos e depois utiliza um
`meu_objeto._todict()` para converte-lo em um dicionário de retorno.

Isso é apenas uma sugestão.

**Comment by wessleysanttos** [comment]
Show de bola mano, faz todo sentido.
